spring:
  application:
    name: hkdc

  datasource:
    url: jdbc:mysql://localhost:3306/hkdc?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: init
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: hkdca432@gmail.com
    password: xorqwqegugmeqenc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true